model:
  name: UNet
  in_channels: 1
  out_channels: 1
  features: [64, 128, 256, 512]

data:
  train:
    type: N2VDataset
    root: ./data/train
    extensions: [".png", ".jpg"]
    patch_size: 64
    masked_fraction: 0.05     # N2V 随机掩蔽比例
    augmentations: true

  val:
    type: ImageDataset
    root: ./data/val
    extensions: [".png", ".jpg"]

trainer:
  max_epochs: 100
  optimizer:
    type: Adam
    lr: 1e-4

  loss:
    type: MSELoss
